---
functional:
  #Главная страница сайта
  - На главной странице сайта пользователь должен иметь возможность ознакомиться с информацией о проекте и его создателях, а так же об участниках (после нажатия на аватар участника осуществляется переход на его страницу на Гитхабе).
  - Пользователи должны иметь возможность пройти процедуру регистрации на проекте с помощью электронной почты на главной странице сайта.
  - Пользователи должны иметь возможность пройти авторизацию на сайте с помощью электронной почты и пароля.
  - Пользователи должны иметь возможность пройти авторизацию на сайте с помощью с помощью Github  или Discord на главной странице сайта.
  - Не авторизованный пользователь должен иметь возможность попробовать свои силы в случайной игре с ботом.
  #Страница проекта Codebattle
  - Авторизованные пользователи должны иметь возможность просмотра рейтингов и статистики других игроков.
  - Авторизованный пользователь должен иметь возможность видеть количество играков в online.
  - Авторизованные пользователи должны иметь возможность создавать новую игру с другим игроком, другом или с ботом. 
  - Авторизованный пользователь должен иметь возможность при создании игры выбрать уровень сложности задачи.
  - Авторизованный пользователь должен иметь возможность при создании игры выбрать время поединка.
  - Авторизованный пользователь должен иметь возможность при создании игры выбрать, как случайную задачу, так и по нужному названию.
  - Авторизованный пользователь должен иметь возможность соревноваться в решении задач с другим игроком принимая вызов от другого игрока.
  - Авторизованные пользователи должны иметь возможность просмотра поединков других играков в реальном времени.
  - Авторизованные пользователи должны иметь возможность участвовать в турнире или просматривать бои  игроков турнира в реальном времени.
  - Авторизованные пользователи должны иметь возможность создавать турнир.
  - Авторизованный пользователь должен иметь возможность отправлять сообщения на сайте игры, как в общем чате, так и личные сообщения пользователям.
  - Авторизованный пользователь должен иметь возможность просматривать и редактировать свой профиль (менять имя, оружие (язык программирования, который указан по умолчанию), пароль к аккаунту при регистрации через Email).
  - Авторизованный пользователь, при наличии подписки, должен иметь возможность просмотривать архив боев.
  #Страница боя
  - Пользователь должен иметь возможность просмотреть обучающую информацию по пользованию сайтом.
  - Пользователь должен иметь возможность выбрать язык для отображения справочной информации к игре (русский или английский).
  - Пользователи должны иметь возможность выбрать удобный язык программирования  для написания кода из представленных.
  - Пользователь должен иметь возможность очистить поле редактора и начать писать код заново.
  - Пользователь должен иметь возможность проверить правильность написанного кода. 
  - Пользователь должен иметь возможность видеть время, которое осталось до окончания игры.
  - Пользователь должен иметь возможность признать свое поражение до окончания игры, в случае если он не может решить задачу.
  - Пользователи должны видеть справочную информацию о сопернике(его рейтинге, очках).
  - Пользователи должны видеть информацию о том, какой язык программирования выбрал соперник.
  - Пользователи должны видеть процесс написание кода друг у друга.
  - Пользователи должны иметь возможность общатся в чате игры.
  - Пользователь должен иметь возможность стать победителем игры, если его код прошел проверку на правильность быстрее кода соперника.
  - После завершения игры кубок победителя должен появиться в поле редактора того игрока, который одержал победу.
  - Проигравший игрок должен увидеть окно с информацией о проигрыше.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным для просмотра  на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  # На сайте должна быть реализована  возможность смены языка всего сайта, а  не только для описания задачи.
  - В ходе игры пользователь должен иметь возможность редактировать только свой код. 
  - Зрители не могут редактировать код участников.
  - Зрители игры могут общаться в чате игры с участниками или с другими зрителями.
  - Зрители и участники не могут редактировать информацию в  описании задачи или в коде задачи.
  - Проверка кода участников должна автоматически проводиться на том языке, который выбрали участники.
  # Пользователь должен иметь возможность удалить аккаунт.